[build-system]
requires = ["setuptools>=38", "wheel", "pybind11>=2.2,<3", 'numpy>=1.17']

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff.lint.per-file-ignores]
"treecorr/__init__.py" = ["F401"]
